### ISSUE TITLE
这里的代码会导致崩溃,但是改成现在这种.会在通知栏显示一个前台通知.

### ISSUE THREAD

**Issue by lydlovezjr** [AndroidyxChen/TodaySteps#2]
![360截图20201021161057215](https://user-images.githubusercontent.com/19246347/96691926-0a246680-13b8-11eb-9dd2-29fa75dedf1d.jpg)
![360截图20201021161223325](https://user-images.githubusercontent.com/19246347/96692074-393ad800-13b8-11eb-9cb1-904476388494.jpg)

**Comment by lydlovezjr** [comment]
有办法解决这个问题吗,佬

**Comment by AndroidyxChen** [comment]
> 有办法解决这个问题吗,佬

抱歉，太久没有更新这个项目，关于通知栏的问题，着急的话建议关注下安卓相关版本的适配，近期我会对通知栏的问题做下适配。

**Comment by Handsome8908** [comment]
大佬 这个问题解决了吗？

**Comment by AndroidyxChen** [comment]
> 大佬 这个问题解决了吗？

jdas

**Comment by AndroidyxChen** [comment]
> 大佬这个问题解决了吗？

目前看起来是这样的，在安卓O也就是Android8.0以上，必须指定当前的ID和NAME，也就是说会有前台通知
